Suffle:
  Snapshot:
    snapshotSavePath: '%FLOW_PATH_DATA%Persistent/fusionSnapshots/'
Neos:
  Flow:
    resource:
      targets:
        localWebDirectoryStaticResourcesTarget:
          target: Suffle\Snapshot\Resource\Target\OverridableFileSystemTarget
